# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
binary_sensor:
  - platform: gpio
    pin: GPIO0
    id: ${rain_sensor_id}
    name: "Rain sensor"
    device_class: moisture
    filters:
      - invert: ${rain_sensor_inverted}
    on_state:
      then:
        - lambda: !include
            file: script_rain_water_tank_sensors_action.yaml
            vars:
              triggered_by: ${rain_sensor_id}
  - platform: gpio
    pin: GPIO1
    id: ${water_tank_empty_id}
    name: "Water tank empty"
    device_class: moisture
    filters:
      - invert: ${water_tank_empty_inverted}
    on_state:
      then:
        - lambda: !include
            file: script_rain_water_tank_sensors_action.yaml
            vars:
              triggered_by: ${water_tank_empty_id}
